[project]
name = "finalproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Vanya88", email = "vanyachen88@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
finalproj = "finalproj:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
